apiVersion: apps/v1
kind: Deployment
metadata:
  name: enketo-redis-cache
  labels:
    app: enketo-redis-cache
spec:
  replicas: 1
  selector:
     matchLabels:
       app: enketo-redis-cache
  template:
    metadata:
      labels:
        app: enketo-redis-cache
    spec:
      containers:
      - name: enketo-redis-cache
        image: redis:5.0.4
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config-cache
            items:
            - key: redis.conf
              path: redis.conf
---
kind: Service
apiVersion: v1
metadata:
  name: enketo-redis-cache
spec:
  selector:
    app: enketo-redis-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP